all:
  hosts:
    smarttv:
      ansible_host: 192.168.1.10
      device_type: smart_tv
    raspberrypi:
      ansible_host: 192.168.1.20
      device_type: server
    smartbulb:
      ansible_host: 192.168.1.30
      device_type: lightbulb
  vars:
    ansible_user: your_username
    ansible_ssh_pass: your_password  #WARNING: Not recommended for production. Use SSH keys.
    location: living_room

smart_devices:
  hosts:
    smarttv:
    smartbulb:
  vars:
    power_source: mains